apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data
  labels:
    storage-type: db-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: storage.edu.local
    path: /db-data
