apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-data-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      storage-type: www-data
