apiVersion: v1
kind: PersistentVolume
metadata:
  name: www-data
  labels:
    storage-type: www-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: storage.edu.local
    path: /www-data
