apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${project.artifactId}
spec:
  rules:
  - host: ${loadbalancer.url}
    http:
      paths:
      - backend:
          serviceName: ${project.artifactId}
          servicePort: 80
