apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-claim
  labels:
    app: wordpress
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      storage-type: db-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-pvc-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      storage-type: www-data